# Generated by Django 6.0.6 on 2026-07-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(choices=[('GEN', 'General Practitioner'), ('PED', 'Pediatrician'), ('DENT', 'Dentist'), ('DERM', 'Dermatologist'), ('GYN', 'Gynecologist'), ('OPT', 'Ophthalmologist'), ('OTHER', 'Other')], default='GEN', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
